### ISSUE TITLE
OS X and Linux

### ISSUE THREAD

**Issue by William-Henrique** [csaez/flascii_bird#2]
"Traceback (most recent call last):
  File "flascii_bird.py", line 18, in <module>
    import msvcrt  # windows-only :_(
ImportError: No module named msvcrt"

Maybe in the future it could work on OS X and Linux! But by now only Windows :(

**Comment by csaez** [comment]
There's a Linux (and possible osx, haven't tested) compatible version too!
Just run the linux suffixed python script.
